#!/usr/bin/env bash
# Transfers a file from our client to a server using 'scp' (Secure Copy).
# Accepts 4 parameters and Strict host key checking is disabled.

if [ $# -ne 1 ]; then
  echo "Usage: $0 <source_file>"
  exit 1
fi

src="$1"

s1="ubuntu@3.84.161.155:~/"
s2="ubuntu@100.25.23.133:~/"

echo "------------------------------------------------------------------------"
scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$src" "$s1"
scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$src" "$s2"
echo "------------------------------------------------------------------------"

if [ $? -eq 0 ]; then
  echo "Success!"
else
  echo "Failed"
fi
